export default [
    {
        title:"首页",
        key:"/home",
        Icon:"home"
    },
    {
        title:"商品",
        key:"/good",
        Icon:"shop",
        children:[
            {
                title:"商品管理",
                key:"/goods",
                Icon:"shop"
            },
            {
                title:"商品分类",
                key:"/category",
                Icon:"shop"
            }
        ]
        
    },{
        title:"用户",
        key:"/user",
        Icon:"user",
        children:[
            {
                title:"用户管理",
                key:"/users",
                Icon:"user"
            }
        ]
    }
]